# config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Markocupic\ContaoFilepondUploader\:
        resource: ../src/
        exclude:
            - ../src/ContaoManager/
            - ../src/DependencyInjection/
            - ../src/Widget/
            - ../src/MarkocupicContaoFilepondUploader.php

    markocupic_contao_filepond_uploader.transfer_key:
        class: Markocupic\ContaoFilepondUploader\TransferKey
        public: true
